[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
gas_reporter = true
gas_reports = ["*"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
